server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

fgv:
  clients:
    spexregister:
      id: "efd9f1fb-387f-4b23-9772-ceab229dca85"
      client-id: "spexregister"
      client-secret: "{noop}a-very-secret-key"
      client-authentication-methods:
        - "client_secret_basic"
      authorization-grant-types:
        - "authorization_code"
        - "refresh_token"
      redirect-uris:
        - "http://127.0.0.1:8080/login/oauth2/code/spexregister-client-oidc"
        - "http://127.0.0.1:8080/authorized"
      scopes:
        - "openid"
        - "profile"
        - "email"
        - "user.read"
        - "user.write"
      client-settings:
        require-authorization-consent: false
        require-proof-key: true
