server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info

spring:
  flyway:
    table: flyway_schema_history_authz
    baseline-on-migrate: true

  jpa:
    open-in-view: false

fgv:
  default-password-encoder-prefix: "bcrypt"
  legacy-password-encoder-prefix: "legacy"
  password-encodings:
    legacy:
      settings:
        algorithm: "SHA-512"
        number-of-iterations: 20
    bcrypt:
      settings:
        strength: 10
  clients:
    spexregister:
      id: "efd9f1fb-387f-4b23-9772-ceab229dca85"
      client-id: "spexregister"
      client-secret: "{noop}a-very-secret-key"
      client-authentication-methods:
        - "client_secret_basic"
      authorization-grant-types:
        - "authorization_code"
        - "refresh_token"
      redirect-uris:
        - "http://127.0.0.1:8080/login/oauth2/code/spexregister-client-oidc"
        - "http://127.0.0.1:8080/authorized"
      post-logout-redirect-uris:
        - "http://127.0.0.1:8080/logged-out"
      scopes:
        - "openid"
        - "profile"
        - "email"
        - "user.read"
        - "user.write"
      client-settings:
        require-authorization-consent: false
        require-proof-key: true
